name: Keep GitHub Streak
on:
  schedule:
    - cron: "*/1 * * * *" # S'exécute toutes les 5 minutes
  workflow_dispatch:
jobs:
  keep-streak:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Git
        run: |
          git config user.name "azalluciano"
          git config user.email "lazaluciano327@gmail.com"
      - name: Do empty commit
        run: |
          git commit --allow-empty -m "🔥 Streak du $(date)"
          git push origin develop
